Performance Comparision


In [12]:
import numpy as np 
import time

size=1_000_000

python_list=list(range(size))
start=time.time()

squared_list=[x**2 for x in python_list]

end=time.time()
print(f"Time for python list is {end-start}seconds")


np_array=np.array(python_list)

start=time.time()
array_squared=np_array**2
end=time.time()
print(f"Time for numpy array is:",{end-start},"seconds")


Time for python list is 0.13701224327087402seconds
Time for numpy array is: {0.003220796585083008} seconds


Memory Usage Comparision

In [15]:
import sys

print("Python list size:",sys.getsizeof(python_list)*len(python_list))
print("Numpy array size:" ,np_array.nbytes)

Python list size: 8000056000000
Numpy array size: 8000000


Creating Numpy arrays :
1.Python list
2.Using inbuilt functions


In [ ]:
#1.Using Python lists

arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape,arr1.dtype)


arr2=np.array([1,2,3.5,4,5,6])
print(arr2)
print(arr2.shape,arr2.dtype)

arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape,arr3.dtype)

[1 2 3 4 5 6]
(6,) int64
[1.  2.  3.5 4.  5.  6. ]
(6,) float64
[[1 2 3]
 [4 5 6]]
(2, 3) int64


In [45]:
#2.Using Built in functions

arr4=np.zeros((3,4))  #3*4 array of 0s
print(arr4)
print(arr4.shape)


arr5=np.ones((3,3),dtype="int64")  #3*3 array of 1s
print(arr5)
print(arr5.shape)

arr6=np.full((4,5),6) #4*5 array of 6s
print(arr6)
print(arr6.shape)

arr7=np.eye(4)  #identity matrix of 4*4
print(arr7)
print(arr7.shape)


arr8=np.linspace(0,10,3)  # equally spaced number (start,end , num=10)
print(arr8)
print(arr8.shape)

arr10=np.arange(0,10,2)  #Elements in range(1,10)
print(arr10)
print(arr10.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(3, 3)
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
(4, 5)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[ 0.  5. 10.]
(3,)
[0 2 4 6 8]
(5,)


Numpy Array Properties


In [42]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr9)

print(arr9.ndim) #No of dimensions
print(arr9.shape) #Dimensions
print(arr9.dtype)   #Datatype object
print(arr9.itemsize) #Size of each element
print(arr9.size) #Total elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int64
8
9


Explictly changing the data type of np arrays

In [48]:
arr11=np.array([1,2,3,4], dtype="U")
print(arr11,arr11.dtype)

float_array=np.array([1,2,3,4,5],dtype="float64")
print(float_array,float_array.dtype)

int_array=float_array.astype(np.int64)
print(int_array,int_array.dtype)

['1' '2' '3' '4'] <U1
[1. 2. 3. 4. 5.] float64
[1 2 3 4 5] int64


Operations on Arrays 

In [55]:
#1.Reshaping 

arr12=np.array([1,2,3,4,5,6])

reshaped_array=arr12.reshape(2,3)
print(reshaped_array)

flattened=arr12.flatten()
print(flattened)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [65]:
#2.Indexing

#Indexing for 1d Array

arr13=np.array([1,2,4,5,6,7,8,9])
print(arr13[5])

#Indexing for 2d arrays

arr14=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr14[2][1])  #8
print(arr14[1][1])  #5

#Fancy Indexing 

arr15=np.array([1,2,3,4,5,6,7,8,9])
idex=[1,5,6]
print(arr15[idex])

7
8
5
[2 6 7]


In [67]:
#3.Slicing

arr16=np.array([1,2,3,4,5,6,7,8,9])

print(arr16[:])
print(arr16[1:5])
print(arr16[::2])
print(arr16[::3])
print(arr16[::4])

print(arr16[::-1])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[1 3 5 7 9]
[1 4 7]
[1 5 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
py_list=[1,2,3,4,5]
copy_list=py_list[1:3]
copy_list[0]=333

print(copy_list)
print(py_list)  #remains same

np_arr=np.array([1,2,3,4,5])
view_arr=np_arr[:4]
view_arr[0]=333

print(view_arr)
print(np_arr)  #changes

np1_arr=np.array([1,2,3,4,5])
copy_arr=np1_arr[:3].copy()
copy_arr[0]=333
print(copy_arr)
print(np1_arr)#remains same



[333, 3]
[1, 2, 3, 4, 5]
[333   2   3   4]
[333   2   3   4   5]
[333   2   3]
[1 2 3 4 5]


Data types in python


In [77]:
arr17=np.array([1,2,3,4,5])
arr18=np.array([6.0,7,8,9,10])
arr19=np.array(["float","hello","AI/ML"])

print(arr17.dtype)
print(arr18.dtype)
print(arr19.dtype)


#Complex Number

arr20=np.array([2+3j])
arr21=np.array([5+3J])
print(arr20+arr21)
print(arr21-arr20)
print(arr20.dtype)
print(arr21.dtype)


#Objects

arr22=np.array(["hello",{"1":"h"},4])
print(arr22.dtype)

int64
float64
<U5
[7.+6.j]
[3.+0.j]
complex128
complex128
object


Vectorization

In [80]:
arr23=np.array([1,2,3,4,5])

sq=arr23**2
print(sq)

arr24=np.array([123,45,67,0,0])
print(arr23+arr24)

[ 1  4  9 16 25]
[124  47  70   4   5]


Broadcasting

In [83]:
#Broadcasting with a Scalar
arr_mul10=arr23*10
print(arr_mul10)

#Broadcasting with a Vector
arr1d=np.array([1,2,3])
arr2d=np.array([[1,2,3],[4,5,6]])

print(arr1d+arr2d)

[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


Multi-Dimensional Arrays

In [94]:
arr1D=np.array([1,2,3])
print(arr1D,arr1D.ndim)

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.ndim)

arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D,arr3D.ndim)




[1 2 3] 1
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 3


In [95]:
print(sum(arr3D))
print(sum(arr2D))

[[ 8 10 12]
 [14 16 18]]
[12 15 18]


In [96]:
sum_of_columns=np.sum(arr2D,axis=1)
print(sum_of_columns)

sum_of_rows=np.sum(arr2D,axis=0)
print(sum_of_rows)



[ 6 15 24]
[12 15 18]


Indexing on 2d and 3d arrays 

In [ ]:
#arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D[0:1][:])


[[1 2 3]]


In [100]:
#arr3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr3D[0][1][1:])  #5,6
print(arr3D[1][1][:2])

[5 6]
[10 11]


Mathematical Functions

In [ ]:
arr25=np.array([1,2,3,4,5])

print(np.sum(arr25))
print(np.prod(arr25))
print(np.min(arr25))
print(np.max(arr25))
print(np.argmin(arr25))
print(np.argmax(arr25))
print(np.mean(arr25))
print(np.var(arr25))
print(np.std(arr25))
print(np.median(arr25))


15
120
1
5
0
4
3.0
2.0
1.4142135623730951
3.0


In [105]:
print(np.square(arr25))
print(np.sqrt(arr25))
print(np.pow(arr25,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [106]:
print(np.log(arr25))
print(np.log10(arr25))
print(np.log2(arr25))
print(np.exp(arr25))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [107]:
print(np.round(2.234))
print(np.ceil(2.234))
print(np.floor(2.234))
print(np.trunc(2.234))

2.0
3.0
2.0
2.0


In [110]:
arr26=np.array([1,2,-3,-4,5,6,6,6,7,7,-23])

print(np.abs(arr26))
print(np.sort(arr26))
print(np.unique(arr26))

[ 1  2  3  4  5  6  6  6  7  7 23]
[-23  -4  -3   1   2   5   6   6   6   7   7]
[-23  -4  -3   1   2   5   6   7]
