### Practice for Numpy

In [1]:
import numpy as np 

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
import time

In [5]:
# Execution Performance 

size=10_000_000

# Python List 

py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"Time for python list is {end-start} seconds")

# Numpy array

np_arr=np.array(py_list)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(f"Time for NumPy array is {end-start} seconds")



Time for python list is 0.9551126956939697 seconds
Time for NumPy array is 0.030450820922851562 seconds


In [6]:
# Memory

import sys

print(f"Size of python list is {sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"Size of numpy array is {np_arr.nbytes} bytes")

Size of python list is 800000560000000 bytes
Size of numpy array is 80000000 bytes


### List

In [7]:
# Create from list

arr1=np.array([1,2,3,4,5])
print(arr1,arr1.dtype,arr1.shape)

arr2=np.array([1,2,3,4,5,'6'])
print(arr2,arr2.dtype,arr2.shape)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.dtype ,arr2d.shape)

[1 2 3 4 5] int64 (5,)
['1' '2' '3' '4' '5' '6'] <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3)


### Built in Functions

In [8]:
arr=np.zeros((3,4),dtype="int64")
print(arr,arr.dtype,arr.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int64 (3, 4)


In [9]:
arr=np.ones((3,4))
print(arr,arr.dtype,arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 (3, 4)


In [10]:
arr=np.full((3,4),69)
print(arr,arr.dtype,arr.shape)

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]] int64 (3, 4)


In [11]:
arr=np.arange(1,10,2)
print(arr,arr.dtype,arr.shape)

[1 3 5 7 9] int64 (5,)


In [12]:
arr=np.linspace(0,10,4)
print(arr,arr.dtype,arr.shape)

[ 0.          3.33333333  6.66666667 10.        ] float64 (4,)


### Numpy array properties 

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
print(arr.dtype) # datatype
print(arr.shape) # dimensions m*n
print(arr.size) # total elements
print(arr.itemsize) # size of each element

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype,float_arr.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
9
8
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64 (3, 3)


### Operations on Numpy array 

In [14]:
# 1. Reshaping 

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped_arr=arr.reshape((3,2))
print(reshaped_arr,reshaped_arr.shape)

flattened=arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [21]:
# 2.Indexing

arr=np.array([1,2,3,4,5])

print(arr[0])
print(arr[4])

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[1][1])
print(arr2d[2][1])

# fancy indexing 
idx=[1,3]
print(arr[idx])

# Boolean indexing 
print(arr2d[arr2d>3])
print(arr[arr>=3])

1
5
5
8
[2 4]
[4 5 6 7 8 9]
[3 4 5]


In [23]:
# 3. Slicing

arr=np.array([1,2,3,4,5])

print(arr[:])
print(arr[1:3])
print(arr[:3])
print(arr[3:])

[1 2 3 4 5]
[2 3]
[1 2 3]
[4 5]


### List vs Copy 

In [25]:
list=[1,2,3,4,5]
sub_list=list[1:3]
print(sub_list)
sub_list[0]=200
print(list)
# list returns a copy -> safe , no change in original list

[2, 3]
[1, 2, 3, 4, 5]


In [27]:
arr=np.array(list)
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(arr)
# Numpy array returns a view of the original data 

sub_arr=arr[1:3].copy()

[2 3]
[  1 200   3   4   5]


### 3D array

In [40]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_cols=np.sum(arr2d,axis=0)
print(sum_of_cols)

sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)

print(arr2d[0:2 ,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [47]:
# 3D Array

arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x3x2
print(arr.shape)
print(arr)

print(arr[:1,1:2,1:])
print(arr[1][1][0])

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[4]]]
9


### Vectorization

In [52]:
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr**2)
print(arr+arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


### Broadcasting

In [54]:
print(arr+5)

[ 6  7  8  9 10]


In [55]:
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr+arr2)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


### Normalization

In [60]:
arr=np.array([[1,2],[3,4]])

print(np.mean(arr))
print(np.std(arr))

mean=np.mean(arr)
std=np.std(arr)

print((arr-mean)/std)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


### Mathematical Functions

### 1. Aggregation functions

In [62]:
arr=np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0


### 2. Power functions

In [65]:
arr=np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(2,2))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
4


### 3. Log and exponential functions

In [70]:
arr=np.array([1,2,3,4,5])

print(np.log(10))
print(np.log10(2))
print(np.log2(2))
print(np.exp(2))

2.302585092994046
0.3010299956639812
1.0
7.38905609893065


### 4. Rounding Functions

In [72]:
arr=np.array([1,2,3,4,5])

print(np.round(2.678))
print(np.ceil(2.678))
print(np.floor(2.678))
print(np.trunc(2.678))

3.0
3.0
2.0
2.0
